
export const movies = [
           {
      id: 1,
      title:      "The Fast and the Furious",
      year:       2001,
      imdbId:     "tt0232500",
      imdbRating: 6.8,
      rating:     6.8,
      plot:       "Los Angeles police officer Brian O'Conner must decide where his loyalty really lies when he becomes enamored with the street racing world he has been sent undercover to end it.",
      type:       "movie",
      rated:      "PG-13",
      url:        "https://m.media-amazon.com/images/M/MV5BZGRiMDE1NTMtMThmZS00YjE4LWI1ODQtNjRkZGZlOTg2MGE1XkEyXkFqcGc@._V1assets/fast-movie 2.jpg",
    },
    {
      id:           2,
      title:        "2 Fast 2 Furious",
      year:         2003,
      imdbId:       "tt0322259",
      imdbRating:   5.9,
      rating:       5.9,
      plot:         "Former cop Brian O'Conner is called upon to bust a dangerous criminal and he recruits the help of a former childhood friend and street racer who has a chance to redeem himself.",
      type:         "movie",
      rated:        "PG-13",
      url:          "https://m.media-amazon.com/images/M/MV5BOTQzYzEwNWMtOTAwYy00YWYwLWE1NTEtZTkxOGQxZTM0M2VhXkEyXkFqcGc@._V1_SX300.jpg",
    },
    {
      id:           3,
      title:        "The Fast and the Furious: Tokyo Drift",
      year:         2006,
      imdbId:       "tt0463985",
      imdbRating:   6.1,
      rating:       6.1,
      plot:         "A teenager becomes a major competitor in the world of drift racing after moving in with his father in Tokyo to avoid a jail sentence in America.",
      type:         "movie",
      rated:        "PG-13",
      url:          "https://m.media-amazon.com/images/M/MV5BMTQ2NTMxODEyNV5BMl5BanBnXkFtZTcwMDgxMjA0MQ@@._V1_SX300.jpg",
    },  
    {
      id:           4,
      title:        "Fast & Furious",
      year:         2009,
      imdbId:       "tt1013752",
      imdbRating:   6.5,
      rating:       6.5,
      plot:         "Brian O'Conner, back working for the FBI in Los Angeles, teams up with Dominic Toretto to bring down a heroin importer by infiltrating his operation.",
      type:         "movie",
      rated:        "PG-13",
      url:          "https://m.media-amazon.com/images/M/MV5BM2Y1YzhkNzUtMzhmZC00OTFkLWJjZDktMWYzZmQ0Y2Y5ODcwXkEyXkFqcGc@._V1_SX300.jpg",
    },
    {
      id:           5,
      title:        "Fast Five",
      year:         2011,
      imdbId:       "tt1596343",
      imdbRating:   7.3,
      rating:       7.3,
      plot:         "Dominic Toretto and his crew of street racers plan a massive heist to buy their freedom while in the sights of a powerful Brazilian drug lord and a dangerous federal agent.",
      type:         "movie",
      rated:        "PG-13",
      url:          "https://m.media-amazon.com/images/M/MV5BMTUxNTk5MTE0OF5BMl5BanBnXkFtZTcwMjA2NzY3NA@@._V1_SX300.jpg",
    },
    {
      id:           6,
      title:        "Fast & Furious 6",
      year:         2013,
      imdbId:       "tt1905041",
      imdbRating:   7.0,
      rating:       7.0,
      plot:         "Hobbs has Dominic and Brian reassemble their crew to take down a team of mercenaries, but Dominic unexpectedly gets sidetracked with facing his presumed deceased girlfriend, Letty.",
      type:         "movie",
      rated:        "PG-13",
      url:          "https://m.media-amazon.com/images/M/MV5BMTM3NTg2NDQzOF5BMl5BanBnXkFtZTcwNjc2NzQzOQ@@._V1_SX300.jpg",
    },
    {
      id:           7,
      title:        "Fast & Furious Presents: Hobbs & Shaw",
      year:         2019,
      imdbId:       "tt6806448",
      imdbRating:   6.4,
      rating:       6.4,
      plot:         "Lawman Luke Hobbs and outcast Deckard Shaw form an unlikely alliance when a cyber-genetically enhanced villain threatens the future of humanity.",
      type:         "movie",
      rated:        "PG-13",
      url:          "https://m.media-amazon.com/images/M/MV5BNmU4OTA5NGYtMTFjMS00MzgxLWFjNTMtYjdlMThlYzc4M2M4XkEyXkFqcGc@._V1_SX300.jpg",
    },
    {
      id:         8,
      title:      "F9: The Fast Saga",
      year:       2021,
      imdbId:     "tt5433138",
      imdbRating: 5.2,
      rating:     5.2,
      plot:       "Dom and the crew must take on an international terrorist who turns out to be Dom and Mia's estranged brother.",
      type:       "movie",
      rated:      "PG-13",
      url:        "https://m.media-amazon.com/images/M/MV5BODJkMTQ5ZmQtNzQxYy00ZWNlLWI0ZGYtYjU1NzdiMjcyNDRmXkEyXkFqcGc@._V1_SX300.jpg"
    },
    {
      id:           9,
      title:        "Fast X",
      year:         2023,
      imdbId:       "tt5433140",
      imdbRating:   5.7,
      rating:       5.7,
      plot:         "Dom Toretto and his family are targeted by the vengeful son of drug kingpin Hernan Reyes.",
      type:         "movie",
      rated:        "PG-13",
      url:          "https://m.media-amazon.com/images/M/MV5BYzEwZjczOTktYzU1OS00YjJlLTgyY2UtNWEzODBlN2RjZDEwXkEyXkFqcGc@._V1_SX300.jpg"
    },
];
